W5D1/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :session
  resources :pokemons
end

W5D1/music_app/app/models/pokemon.rb
class Pokemon < ApplicationRecord
  validates :name, presence: true
end

W5D1/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, uniqueness: true, presence: true
  validates :password_digest, presence: { message: "cannot be blank!" }
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token
  before_validation :downcase_email

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def downcase_email
    self.email = self.email.downcase
  end
end

W5D1/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def log_in_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  private

  def require_user!
    unless logged_in?
      flash[:errors] = ["Must be logged in!"]
      redirect_to new_session_url
    end
  end
end

W5D1/music_app/app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :require_user!

  def index
    @pokemons = Pokemon.all
    render :index
  end

  def show
    @pokemon = Pokemon.find_by(id: params[:id])

    if @pokemon
      render :show
    else
      flash[:errors] ||= []
      flash[:errors] += ["Pokemon could not be found!"]
      redirect_to pokemons_url
    end
  end

  def new
    @pokemon = Pokemon.new

    render :new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)

    if @pokemon.save
      redirect_to pokemon_url(@pokemon)
    else
      flash.now[:errors] = @pokemon.errors.full_messages
      render :new
    end
  end

  def edit
    @pokemon = Pokemon.find_by(id: params[:id])

    render :edit
  end

  def update
    @pokemon = Pokemon.find_by(id: params[:id])

    if @pokemon.update(pokemon_params)
      redirect_to pokemon_url(@pokemon)
    else
      flash.now[:errors] = @pokemon.errors.full_messages
      render :edit
    end
  end

  def destroy
    @pokemon = Pokemon.find_by(id: params[:id])
    @pokemon.delete

    redirect_to pokemons_url
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name)
  end
end

W5D1/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    params[:user][:email] = params[:user][:email].downcase if params[:user][:email]

    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Incorrect email/password"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

W5D1/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])

    render :show
  end

  private

  def user_params
    params[:user][:email] = params[:user][:email].downcase if params[:user][:email]
    params.require(:user).permit(:email, :password)
  end
end

W5D1/music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"<%= form_authenticity_token %>\">".html_safe
  end
end

W5D1/music_app/app/helpers/pokemons_helper.rb
module PokemonsHelper
end

W5D1/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D1/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <div class="header-container">

      <img class="pikachu" src="/assets/5Pikachu.png" alt="pikachu">

      <% if logged_in? %>
        <div class="username">
          Welcome <%= current_user.email  %>!
        </div>
      <% end %>
      <% if logged_in? %>
        <div class="flexor">
            <%= button_to 'Sign Out', session_url, method: :delete %>
        </div>
      <% else %>
        <div class="flexor">
          <div class="buttons">
            <%= link_to 'Sign In', new_session_url %>
          </div>
          <div class="buttons">
            <%= link_to 'Sign Up', new_user_url %>
          </div>
        </div>
      <% end %>
    </div>

    <header class="music-app">
      <img src="/assets/Pokeball.png" alt="pokeball">
      Pokemon App
      <img src="/assets/Pokeball.png" alt="pokeball">
    </header>

    <%= yield :title %>

    <% if flash[:errors] %>
      <ul class="errors">
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>

    <%= yield %>
  </body>
</html>

W5D1/music_app/app/views/shared/_form.html.erb
<% if action == :signin %>
  <% message = 'Sign In' %>
  <% actions_url = session_url %>
<% else %>
  <% message = 'Sign Up' %>
  <% actions_url = users_url %>
<% end %>

<div class="form-container">
  <form class="sign-form" action="<%= actions_url %>" method="post">
    <%= auth_token %>

    <div class="username-container">
      <i class="fa fa-envelope-o" aria-hidden="true"></i>
      <label class="form-label" for="email">Email: </label>
      <input id="email" type="text" name="user[email]" value="">
    </div>

    <br>

    <div class="password-container">
      <label class="form-label" for="password">Password: </label>
      <input id="password" type="password" name="user[password]" value="">
    </div>

    <br>

    <input class="buttons button-right" type="submit" value="<%= message %> Now">
  </form>
</div>

W5D1/music_app/app/views/shared/_pokemon.html.erb
<div class="pokemon-form">
  <div>
    <%= pokemon.name %>
  </div>
  <%= button_to 'Delete Pokemon :(', pokemon_url(pokemon), method: :delete %>
</div>

W5D1/music_app/app/views/shared/_pokemon_form.html.erb
<% if action == :new %>
  <% message = 'Add Pokemon!' %>
  <% action_url = pokemons_url %>
<% else %>
  <% message = 'Update Pokemon' %>
  <% action_url = pokemon_url(pokemon.id) %>
<% end %>

<div class="pokemon-form-container">
  <form class="pokemon-form" action="<%= action_url %>" method="post">
    <%= auth_token %>

    <% if action == :edit %>
      <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <div class="name-container">
      <label class="form-label" for="name">Name: </label>
      <input id="name" type="text" name="pokemon[name]" value="<%= pokemon.name %>">
    </div>

    <br>

    <input class="buttons button-center" type="submit" value="<%= message %>">
  </form>
</div>

W5D1/music_app/app/views/users/new.html.erb
<%= render "shared/form", action: :signup %>